source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'sqlite3'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

gem 'haml-rails'

gem 'nifty-generators', :group => :development
gem 'rspec-rails', :group => [:test, :development]

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara', :git => 'git://github.com/jnicklas/capybara.git'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'spork', :git => 'git://github.com/timcharper/spork.git'
  gem 'pickle'
end

